# Generated by Django 5.1 on 2024-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'coming soon'), (3, 'finish'), (4, 'in active')], default=1),
        ),
    ]
