# Generated by Django 5.1 on 2024-08-26 17:21

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(book.models.Status['ACTIVE'], 'active'), (book.models.Status['COMING_SOON'], 'coming soon'), (book.models.Status['FINISH'], 'finish'), (book.models.Status['INACTIVE'], 'in active')], default=1),
        ),
    ]
